"""Archive subsystem — generate permanent reference pages for Clean and
Promising domains via the shared LLM backend, then commit + push.

Independent of the daily pipeline. Runs ~10 minutes after pipeline
completion via its own systemd timer / cron entry:

    10 7 * * * cd /home/domainsifter/domainsifter && \\
      .venv/bin/python -m scripts.archive_generator \\
      >> /var/log/domainsifter/archive.log 2>&1

Reads:
  - scripts/config.json             (--config; carries llm.* + archive_generator.*)
  - src/data/daily-domains.json     (pipeline output)
  - src/data/archive-index.json     (master index; created empty on first run)
  - src/data/wayback_excerpts.json  (excerpt sidecar; path from config)
  - env GITHUB_TOKEN                (required for the push)

Writes:
  - src/content/archive/{name}.md  (one Markdown file per new archive entry)
  - src/data/archive-index.json    (appended in place)

2026-09-19 — THREE CHANGES

1. BACKEND. The direct `anthropic` client is gone. Generation now goes
   through `scripts.llm_backend.get_backend(config)`, the same interface
   `phase2_ranker` and `snapshot_classifier` use, so the subscription-backed
   `claude_code` backend and the metered `api` backend are one config value
   apart (hard rule 9). This module stopped producing pages on 2026-07-21
   when the API credit balance hit zero; ANTHROPIC_API_KEY is no longer a
   gate here — the backend decides.

2. GROUNDING. The page prompt now has two explicit modes. With a Wayback
   excerpt the page states what the site WAS, quoting/paraphrasing the real
   title, meta description and headings. WITHOUT one it writes a shorter,
   purely factual page from the numeric signals and says outright that the
   historical content could not be retrieved. Speculation from the domain
   name ("the name suggests possible connections to fitness, productivity,
   entertainment, or educational content") is forbidden in both modes —
   under hard rule 2 a guess presented as fact is an invented fact. A live
   rehearsal the same day leaked the banned phrase anyway, on the GROUNDED
   path, for a domain whose only capture was a parking placeholder; the
   prompt was restructured in response. See the revision comment above
   `MODE_MARKER_GROUNDED` for the diagnosis and the four fixes.

3. EVIDENCE IN FRONTMATTER. The ranker's `phase2_reason`, the classifier's
   `snapshot_category`, and the archived page's title / meta description /
   h1 / h2 are now persisted into the frontmatter as OPTIONAL keys. They are
   read live nowhere: daily-domains.json is a 14-day rolling window and
   wayback_excerpts.json only covers what the classifier saw, while an
   archive page is permanent — none of the 113 pages written before this
   date still appear in the daily list, so a live read would show the
   evidence for two weeks and then drop it on the next rebuild. See
   `_evidence_fields`.

Behavior:
  1. Load daily-domains.json.
  2. Filter to entries with verdict in {Clean, Promising} AND not already
     in archive-index (the index is source of truth for "already archived").
  3. For each qualifying entry: resolve its Wayback excerpt (sidecar first,
     per-domain fetch as fallback), call the backend, write {name}.md with
     Astro frontmatter + the generated body.
  4. Append each new entry to archive-index.json.
  5. Atomic file writes — temp-write + os.replace — so a mid-run failure
     never leaves a partial index.
  6. git add + commit ("archive: add N new pages for {date}") + git push.
     Token goes in the push argv ONLY, not git config (matches
     scripts/run-daily.sh).

Failure modes:
  - Per-domain backend failure (LLMBackendError or anything else) → log,
    skip the domain, continue with others. The failed domain stays out of
    archive-index; it is retried on the next run.
  - 5 consecutive failures → circuit breaker opens, exit non-zero (cron /
    log monitor will surface it). Threshold is config-driven.
  - git push failure → exit non-zero. Local commit is left in place; next
    day's run will see a clean state again after the operator resolves
    the push (typically a manual pull --ff-only).
  - Idempotent on re-run: never regenerate an existing .md file. The
    archive-index is the source of truth.

Sitemap: NOT regenerated here. The @astrojs/sitemap integration walks all
built pages including the dynamic /d/{name} routes on the next Astro
build (triggered by the push that this script makes). robots.txt already
points to sitemap-index.xml. This script does not write public/sitemap.xml.

Frontmatter: the YAML block is generated by `_build_frontmatter`, NOT by
the model, and its keys are the zod schema in src/content/config.ts. The
first thirteen keys are the original required contract; renaming or
reordering one breaks the Astro content-collection build. The evidence keys
added in change 3 are optional on both sides and are omitted entirely when
absent, which is what keeps the 113 pages that predate them valid. The
excerpt values are untrusted third-party text and go through
`_clean_untrusted_text` + `_yaml_quote` before they are written.

Operational notes — see commit message header.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
import tempfile
import time
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

from scripts import llm_backend
from scripts.wayback_excerpt import fetch_excerpt

logger = logging.getLogger("scripts.archive_generator")


# --- Constants ---------------------------------------------------------------

CONSECUTIVE_FAILURES_ABORT = 5

QUALIFYING_VERDICTS = ("Clean", "Promising")

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "scripts" / "config.json"
DAILY_DOMAINS_PATH = REPO_ROOT / "src" / "data" / "daily-domains.json"
ARCHIVE_INDEX_PATH = REPO_ROOT / "src" / "data" / "archive-index.json"
ARCHIVE_CONTENT_DIR = REPO_ROOT / "src" / "content" / "archive"
# Sidecar with pre-computed Wayback excerpts (Phase 4, 2026-05-20). Written
# by scripts/pipeline.py's Stage 4b classifier; archive_generator reads it
# instead of refetching from archive.org, eliminating ~60s of wall-clock per
# day's archive run. Falls back to per-domain fetch_excerpt for any name
# not present in the sidecar (covers backfilled carryover from before
# Phase 4 + transient sidecar-write failures). Overridable via config key
# `sidecar_excerpts_path`.
SIDECAR_EXCERPTS_PATH = REPO_ROOT / "src" / "data" / "wayback_excerpts.json"

GITHUB_REPO_URL_TEMPLATE = "https://x-access-token:{token}@github.com/oiramix/domainsifter.git"
GIT_USER_NAME = "domainsifter-archive"
GIT_USER_EMAIL = "99090280+oiramix@users.noreply.github.com"


# --- Config (hard rule 9) ----------------------------------------------------

# Applied when a key is absent from config["archive_generator"], so the module
# behaves sensibly before the keys land in scripts/config.json.
DEFAULTS: dict[str, Any] = {
    # Sidecar of pre-computed Wayback excerpts, relative to the repo root
    # (absolute paths are honoured as-is).
    "sidecar_excerpts_path": "src/data/wayback_excerpts.json",
    # Per-page wall-clock cap handed to the backend. None → llm.timeout_seconds.
    "timeout_seconds": None,
    # Circuit breaker: consecutive per-domain failures that abort the run.
    "consecutive_failures_abort": CONSECUTIVE_FAILURES_ABORT,
    # Caps on the untrusted excerpt text persisted into frontmatter. These
    # mirror MAX_FIELD_CHARS / MAX_HEADING_CHARS / MAX_HEADINGS in
    # src/pages/d/[domain].astro so the page's own truncation is a no-op on
    # what we write (no double ellipsis) and one 40 kB spam heading can't
    # bloat a permanent .md file.
    "excerpt_max_field_chars": 300,
    "excerpt_max_heading_chars": 140,
    "excerpt_max_headings": 5,
}

# The ranker writes this into phase2_reason when a name was sent to the model
# but came back absent from the reply. It is a pipeline marker, not a
# justification, and must never reach a page. scripts/output.py filters it on
# the JSON side; duplicated (not imported) here because this module must stay
# correct against any daily-domains.json, including ones written before that
# filter existed.
PHASE2_REASON_PLACEHOLDER = "missing from response"


def cfg(config: dict | None, key: str) -> Any:
    """Read ``config["archive_generator"][key]``.

    Falls back to a top-level key of the same name (so an operator who adds
    ``sidecar_excerpts_path`` at the root of config.json still gets the
    behaviour they intended), then to DEFAULTS.
    """
    section = (config or {}).get("archive_generator")
    if isinstance(section, dict) and key in section:
        return section[key]
    if isinstance(config, dict) and key in config:
        return config[key]
    return DEFAULTS[key]


def _sidecar_path_from_config(config: dict | None) -> Path:
    """Resolve the excerpt sidecar path, relative paths against REPO_ROOT."""
    raw = cfg(config, "sidecar_excerpts_path")
    if not raw:
        return SIDECAR_EXCERPTS_PATH
    path = Path(str(raw))
    return path if path.is_absolute() else REPO_ROOT / path


# --- System prompt -----------------------------------------------------------
#
# 2026-09-19 revision. Two modes, chosen by the caller from the excerpt, not
# by the model from a conditional buried in one long prompt:
#
#   GROUNDED    — a Wayback excerpt with real content exists. The page says
#                 what the site WAS, from the excerpt's own title / meta /
#                 h1 / h2.
#   NO-EXCERPT  — nothing was retrievable. The page is SHORTER, sticks to the
#                 numeric signals, and states plainly that the historical
#                 content could not be retrieved.
#
# The previous single prompt told the model to OMIT the historical section
# when ungrounded, which readers experienced as an unexplained gap; and its
# earlier ancestor invited "the name suggests…" speculation, which is what
# produced the 4minutes.net page this rewrite exists to replace.
#
# 2026-09-19, second revision — MEASURED LEAK. A live rehearsal produced
# "The domain's name suggests a connection to a filmmaker … but the excerpt
# itself provides no content evidence" on a domain whose only capture was a
# registrar parking placeholder. Diagnosis, and what each part of the fix
# answers:
#
#   a) The ban lived in _SYSTEM_PROMPT_COMMON as bullet 2 of 7 under
#      ABSOLUTE PROHIBITIONS, stated once and then buried under six numbered
#      sections of positive drafting instructions. NO-EXCERPT restated it
#      three times in its own block; GROUNDED restated it zero times. The
#      leaking generation was GROUNDED. → The rule is now its own named
#      section (THE EVIDENCE RULE) at the END of the common block, and BOTH
#      mode blocks close with a BEFORE YOU RETURN THE PAGE recheck, so the
#      last thing read before drafting is the rule, in either mode.
#
#   b) The rule was negative only — a list of banned phrases. A phrase list
#      is satisfiable by paraphrase, and the underlying MOVE (inferring
#      purpose from the name) was never named as the thing forbidden. → The
#      rule now leads with the positive form: every claim about what the
#      site was must be traceable to a named `wayback_excerpt` field.
#
#   c) The observed sentence hedged itself in the same breath, which reads
#      as compliance. → The rule now says outright that a hedge does not
#      rescue a guess, quoting the shape of the observed failure.
#
#   d) A placeholder capture routes to GROUNDED (it IS content), where the
#      250-400 word target, the "at least 4 mentions" quota and a mandatory
#      "### Historical use" section demand more prose than the evidence can
#      supply — structural pressure to backfill from the only other string
#      available, the name. → PLACEHOLDER AND PARKED CAPTURES states that a
#      parking page is evidence the domain was PARKED and nothing more, and
#      both mode blocks now say the word target is a ceiling on padding
#      rather than a quota, so the correct way out of that conflict is a
#      shorter page.
#
# Word targets, section order, frontmatter emission and every other
# prohibition are unchanged.

MODE_MARKER_GROUNDED = "MODE: GROUNDED"
MODE_MARKER_NO_EXCERPT = "MODE: NO-EXCERPT"

_SYSTEM_PROMPT_COMMON = """You are writing reference pages for DomainSifter, a domain-research service that publishes daily evaluations of recently-dropped (expired) domains. Each page documents one specific domain at the moment it became available for re-registration: what the site was, what authority signals it carries, and DomainSifter's verdict.

INPUT
The user turn contains one JSON record for a single domain. Its `wayback_excerpt` field, when present, holds text scraped from the last archived snapshot of the site: `title`, `meta_description`, `h1` (a list) and `h2` (a list). That excerpt is the ONLY evidence available about what the site was. When it is absent there is no evidence at all. Either way, THE EVIDENCE RULE below governs every sentence you write about the site.

OUTPUT FORMAT
Return only the Markdown body, starting with the `##` heading. No frontmatter, no preamble, no meta-commentary, no closing question. The generator script adds the frontmatter.

TONE
Neutral, factual, encyclopedic. It should read like a reference entry, not like marketing copy or an AI assistant talking. No exclamation marks. Every sentence must carry specific information.

ABSOLUTE PROHIBITIONS — a page that breaks any of these is unpublishable
- Never invent a fact. When a field is missing, null or zero, say so plainly or leave it out.
- Never write marketing or promotional claims: no "great investment", "strong potential", "perfect for", "unlock", "imagine", no calls to action beyond the closing verification line.
- Never state or imply traffic figures, visitor numbers, revenue, resale price, appraisal or valuation of any kind. None of that is in the record.
- Never invent testimonials, reviews, endorsements, rankings, awards or any other social proof.
- Never use generic AI filler ("In today's digital landscape", "Discover the potential of", "Unlock the power of").

NON-ENGLISH CONTENT
Excerpts are frequently not in English — Chinese, German, Russian and Japanese are all common. When the excerpt is not in English:
- Write the page in English and DESCRIBE the content: name the language, and say in English what the title, description and headings are about.
- Do NOT paste an untranslated foreign-language string and present it as the site's brand, tagline or English name. A short quoted fragment is acceptable only when you immediately translate or gloss it in English.
- The script a site was written in is not itself a signal of quality, legitimacy or abuse. Do not treat it as one.

DOMAIN NAME USAGE
Always write the domain with its TLD ("example.net", not "example"). The first sentence must contain the full domain name exactly as a buyer would search it. Printing the name is not the same as reasoning from it — see the next section.

THE EVIDENCE RULE — the rule that actually gets broken, so it is stated last and in full
Positively: every statement on the page about what the site WAS, hosted, sold, covered, offered or served must be traceable to one named field of `wayback_excerpt` — the title, the meta_description, an h1 or an h2. Before writing such a sentence, name to yourself the field it comes from. If you cannot name one, the sentence does not go on the page.
Negatively: the domain is a string, not a source. The name is not evidence. Nothing about the site's purpose, audience, industry, tone or content may be inferred from the name, from the words or fragments inside it, from its word structure, or from its TLD. The phrases "the name suggests", "based on the name structure", "the linguistic composition suggests", "likely operated as", "may have served", "could have been used for", "points to a connection with", "hints at", "presumably", "appears to have been" and anything equivalent to them are forbidden anywhere on the page, in either mode.
A hedge does not rescue a guess. "The name suggests a connection to a filmmaker, but the excerpt provides no content evidence of what the site actually was" is a full violation, not a careful sentence: the guess has been published and the qualifier merely records that you knew it was one. Delete the guess and keep the disclaimer.
Never offer several possibilities at once. "Possible connections to fitness, productivity, entertainment, or educational content" is four guesses in one sentence and breaks this rule four times over.

PLACEHOLDER AND PARKED CAPTURES
A parking page, a domain-for-sale notice, a registrar or web-host default page, a "coming soon" splash and an error page are all genuine findings — and each is a finding about exactly one thing: the state of the domain at the moment of that capture. Report that and stop ("the final capture showed a parked-page placeholder rather than active content").
Such a capture says nothing whatsoever about whatever the site may have been before it. What preceded a placeholder is unrecorded, and unrecorded is unknown. Holding a placeholder excerpt is NOT a licence to reconstruct the site that came before it, and it is not a lesser standard of evidence: THE EVIDENCE RULE applies to a placeholder capture exactly as it applies to a missing one. A page whose only evidence is a placeholder is a short page, and a short page is the correct output.
"""

_SYSTEM_PROMPT_GROUNDED = """
MODE: GROUNDED
A Wayback excerpt with real content is attached to this record. Write the FULL page: 250-400 words of clean Markdown, sections in this exact order. The domain name must appear naturally at least 4 times across the page.

1. `## ` heading: the domain name as plain text, nothing else. This is the H2.

2. Lead paragraph (40-60 words): what the domain is, when it became available, one clause saying what the site was according to the excerpt, and DomainSifter's verdict. When the excerpt is a placeholder, that clause says the capture was a placeholder — it does not reach past it.

3. `### Authority and historical presence`
   2-3 short paragraphs interpreting the Wayback snapshot count, the OpenPageRank score and the Common Crawl source-domain count in plain language, tying each number to what it means for someone considering registering this domain. Mix prose with the numbers rather than listing them. Keep the description of the site's content out of this subsection — it belongs in the next one.

4. `### Historical use`
   1-2 paragraphs describing what the site WAS, grounded ONLY in the excerpt's title, meta_description, h1 and h2:
   - State the subject of the site directly, in the past tense, citing the title and meta description. Quote them where quoting is clearer than paraphrase.
   - Say what the h1 and h2 headings reveal about the site's structure or topical focus.
   - Do not extrapolate past the excerpt. If it shows a recipe index, the site had a recipe index; it does not follow that the site "also offered meal planning".
   - Note the date of the snapshot the excerpt came from, so a reader knows how current the description is.
   - PLACEHOLDER CAPTURES. When the title or meta description shows a parked page, a domain-for-sale notice, a generic placeholder or an error page, that IS the whole of the finding: report it, date it, do not dress it up, and stop there. You have an excerpt but you do not have a site, and holding some evidence is never a licence to fill in around it. The name is still not evidence. Two or three sentences is the correct length for this section in that case.

5. `### Why we labeled this {verdict}`
   2-3 sentences explaining the verdict in terms a domain buyer cares about, referencing the actual quantitative signals. For Clean, name the positive signals that justified the highest confidence. For Promising, name both the strengths and the limitations.

6. Closing line: one sentence noting that the evaluation reflects the state on the dropped date, that availability changes quickly, and that the reader should verify the current status with a registrar.

BEFORE YOU RETURN THE PAGE
Reread sections 2 and 4. For every clause that states what the site was, name the excerpt field it came from. Any clause you cannot source comes out — with or without a hedge attached — and most especially one that echoes the words inside the domain name back at the reader. The 250-400 word target is a ceiling on padding, not a quota to fill: a page grounded in a thin or placeholder excerpt is correctly shorter, and shortening it is always the right way to resolve the conflict.
"""

_SYSTEM_PROMPT_NO_EXCERPT = """
MODE: NO-EXCERPT
No archived content could be retrieved for this domain: either no usable Wayback snapshot exists or the snapshot carried no title, description or headings. You therefore have NO evidence whatsoever about what the site was, and you must not fill the gap with a guess.

Write a SHORTER, purely factual page: 120-200 words of clean Markdown, sections in this exact order. The domain name must appear naturally at least 3 times.

1. `## ` heading: the domain name as plain text. This is the H2.

2. Lead paragraph (30-50 words): the domain, when it became available, and DomainSifter's verdict. Do not characterise the site.

3. `### Authority and historical presence`
   1-2 paragraphs using ONLY the numbers present in the record: Wayback snapshot count, the date of the most recent snapshot, OpenPageRank, Common Crawl source-domain count, certificate history. Say what each number does and does not establish. A field that is null or zero is reported as absent, never glossed over and never estimated.

4. `### Historical use`
   One or two sentences, and nothing more: state plainly that the archived content of the site could not be retrieved, and that DomainSifter therefore makes no claim about what the site hosted. Do not describe, characterise, hint at or guess the content. Do not restate the snapshot count here. Do not speculate from the domain name — the name is not evidence.

5. `### Why we labeled this {verdict}`
   2 sentences grounding the verdict in the quantitative signals only, and acknowledging that the absence of retrievable content is itself a limitation on the evaluation.

6. Closing line: one sentence noting that the evaluation reflects the state on the dropped date, that availability changes quickly, and that the reader should verify the current status with a registrar.

BEFORE YOU RETURN THE PAGE
Reread it for any clause that states, implies or hints at what the site was. There is no excerpt field any such clause could be sourced from, so every one of them comes out — with or without a hedge attached, and most especially one that echoes the words inside the domain name back at the reader. The 120-200 word target is a ceiling on padding, not a quota to fill: this page is allowed to be short, and it is allowed to say plainly that we do not know.
"""


def build_system_prompt(has_excerpt: bool) -> str:
    """Pick the grounded or the no-excerpt page contract.

    Splitting the two modes into separate prompts (rather than one prompt
    with a conditional) means the model never sees the instructions for the
    branch it is not in, which is what keeps "no evidence" pages from
    drifting back into description.
    """
    tail = _SYSTEM_PROMPT_GROUNDED if has_excerpt else _SYSTEM_PROMPT_NO_EXCERPT
    return _SYSTEM_PROMPT_COMMON + tail


# --- Pure helpers (unit-tested) ---------------------------------------------


def _filter_qualifying(
    domains: list[dict], already_archived: set[str],
) -> list[dict]:
    """Verdict in {Clean, Promising} AND name not already archived. Domains
    without a verdict (legacy payloads) are rejected — the archive only
    contains entries we've explicitly labeled."""
    out: list[dict] = []
    for d in domains:
        verdict = d.get("verdict")
        if verdict not in QUALIFYING_VERDICTS:
            continue
        name = d.get("name")
        if not name or name in already_archived:
            continue
        out.append(d)
    return out


def _slug_for(name: str) -> str:
    """Filename slug for src/content/archive/{slug}.md. Preserves dots so
    the Astro dynamic route param matches verbatim ('deepsand.net.md' →
    /d/deepsand.net). Lowercased; whitespace stripped; anything that
    isn't a safe filename character (alnum / . / - / _) is rejected by
    raising. We never construct domain names ourselves — they come from
    daily-domains.json which the pipeline normalises — so this is a
    sanity gate, not a sanitiser."""
    s = name.strip().lower()
    if not s:
        raise ValueError("empty name")
    for ch in s:
        if not (ch.isalnum() or ch in ".-_"):
            raise ValueError(f"unsafe character {ch!r} in name {name!r}")
    return s


def _excerpt_has_content(excerpt: dict | None) -> bool:
    """True when the excerpt carries at least one usable content field.

    A snapshot whose title / meta / h1 / h2 are all empty is evidence of
    nothing, so it routes to the NO-EXCERPT prompt exactly like a missing
    excerpt does. Metadata (snapshot_timestamp, snapshot_url) does not
    count — it says when we looked, not what we found.
    """
    if not isinstance(excerpt, dict):
        return False
    if (excerpt.get("title") or "").strip():
        return True
    if (excerpt.get("meta_description") or "").strip():
        return True
    for key in ("h1", "h2"):
        values = excerpt.get(key) or []
        if isinstance(values, list) and any(str(v).strip() for v in values):
            return True
    return False


def _excerpt_for_prompt(excerpt: dict | None) -> dict | None:
    """Normalise the excerpt to the fields the page may be grounded in.

    snapshot_url is dropped (a web.archive.org URL in the prompt invites the
    model to write about archive.org rather than the site); snapshot_timestamp
    is kept because the page cites how current the description is.
    """
    if not _excerpt_has_content(excerpt):
        return None
    assert isinstance(excerpt, dict)  # narrowed by _excerpt_has_content
    return {
        "title": excerpt.get("title"),
        "meta_description": excerpt.get("meta_description"),
        "h1": excerpt.get("h1") or [],
        "h2": excerpt.get("h2") or [],
        "snapshot_timestamp": excerpt.get("snapshot_timestamp"),
    }


def _build_user_message(record: dict, excerpt: dict | None = None) -> str:
    """The user turn sent alongside the system prompt.

    JSON-pretty so the model can pattern-match fields without ambiguity, and
    ensure_ascii=False so a Chinese or German excerpt arrives as readable text
    instead of \\uXXXX escapes (the model is asked to describe it in English,
    which it cannot do from escapes).

    The leading mode line repeats the system prompt's branch so the
    instruction survives a long record, and gives the tests a stable hook.
    """
    grounded = _excerpt_for_prompt(excerpt)
    enriched = {**record, "wayback_excerpt": grounded}
    if grounded is not None:
        header = (
            f"{MODE_MARKER_GROUNDED} — this record has a Wayback excerpt. "
            f"Describe what the site was using only that excerpt; if the "
            f"excerpt is a parked or placeholder capture, that is the whole "
            f"finding. Do not speculate from the domain name."
        )
    else:
        header = (
            f"{MODE_MARKER_NO_EXCERPT} — no archived content was retrievable "
            f"for this domain. Write the short factual page and state that the "
            f"historical content could not be retrieved. Do not speculate."
        )
    return (
        f"{header}\n\n"
        "Generate the archive page for this domain:\n\n"
        + json.dumps(enriched, indent=2, sort_keys=True, ensure_ascii=False)
    )


def _is_unsafe_char(ch: str) -> bool:
    """C0/C1 control characters and the bidi embedding/override/isolate family.

    Controls would need escaping in YAML; the bidi family is worse, because it
    silently reorders the text printed around it. Same set that
    src/pages/d/[domain].astro strips on the rendering side.
    """
    code = ord(ch)
    return (
        code < 0x20
        or 0x7F <= code <= 0x9F
        or 0x202A <= code <= 0x202E
        or 0x2066 <= code <= 0x2069
    )


def _clean_untrusted_text(value: Any, max_chars: int) -> str | None:
    """Normalise one piece of third-party archived text for storage.

    Excerpts come from spam pages as often as from real ones. Strip control
    and bidi characters, collapse whitespace (which also removes the newlines
    that would otherwise have to survive a YAML round-trip), and cap the
    length INCLUDING the ellipsis so the page's own 300-char truncation never
    fires a second time and produces "...…".

    Returns None for non-strings and for anything that is empty after
    cleaning — callers omit the key entirely rather than writing null.
    """
    if not isinstance(value, str):
        return None
    stripped = "".join(" " if _is_unsafe_char(ch) else ch for ch in value)
    stripped = " ".join(stripped.split())
    if not stripped:
        return None
    if len(stripped) > max_chars:
        stripped = stripped[: max_chars - 1].rstrip() + "…"
    return stripped


def _yaml_quote(value: str) -> str:
    """Render a string as a YAML double-quoted scalar.

    Double-quoted is the one YAML style that can hold any character, so a
    stray quote, colon, hash, leading dash or newline in an untrusted excerpt
    cannot terminate the scalar and corrupt the frontmatter (which would fail
    `npm run build` for the whole site, not just one page). Non-ASCII is
    emitted as itself — the file is UTF-8 and js-yaml reads it as such — so a
    Chinese title stays legible in the repo.
    """
    out = [
        '"',
    ]
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or 0x7F <= ord(ch) <= 0x9F:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _yaml_string_list(values: list[str]) -> str:
    """Flow-style sequence of quoted scalars: ["a", "b"]."""
    return "[" + ", ".join(_yaml_quote(v) for v in values) + "]"


def _phase2_reason(record: dict, max_chars: int) -> str | None:
    """The ranker's justification, or None when there isn't a real one.

    None covers: field absent (fallback days, pre-2026-09-19 carryover),
    non-string junk, whitespace-only text, and the "missing from response"
    placeholder. Mirrors scripts/output.py::_phase2_reason.
    """
    raw = record.get("phase2_reason")
    if not isinstance(raw, str):
        return None
    if raw.strip().lower() == PHASE2_REASON_PLACEHOLDER:
        return None
    return _clean_untrusted_text(raw, max_chars)


def _evidence_fields(
    record: dict, excerpt: dict | None, config: dict | None = None,
) -> dict[str, Any]:
    """The optional evidence block appended to the frontmatter.

    WHY THIS IS IN THE MARKDOWN AND NOT READ LIVE (2026-09-19):
    daily-domains.json is a 14-day rolling window and wayback_excerpts.json
    only covers domains the classifier has seen, while an archive page is
    permanent — today none of the 113 existing pages still appear in the
    daily list. Reading the evidence live means it shows for two weeks and
    then vanishes on a rebuild. Written here, it is captured once, at the
    moment we knew it, and kept.

    Every key is omitted when absent. The zod schema in
    src/content/config.ts marks all of them optional and nullable, because
    the 113 pages written before this change have none of them and a
    required field fails the site build.
    """
    field_cap = int(cfg(config, "excerpt_max_field_chars"))
    heading_cap = int(cfg(config, "excerpt_max_heading_chars"))
    max_headings = int(cfg(config, "excerpt_max_headings"))

    out: dict[str, Any] = {}

    reason = _phase2_reason(record, field_cap)
    if reason:
        out["phase2_reason"] = reason

    category = record.get("snapshot_category")
    if isinstance(category, str) and category.strip():
        out["snapshot_category"] = category.strip()

    if not isinstance(excerpt, dict):
        return out

    title = _clean_untrusted_text(excerpt.get("title"), field_cap)
    if title:
        out["excerpt_title"] = title
    meta = _clean_untrusted_text(excerpt.get("meta_description"), field_cap)
    if meta:
        out["excerpt_meta_description"] = meta
    for src_key, dest_key in (("h1", "excerpt_h1"), ("h2", "excerpt_h2")):
        raw = excerpt.get(src_key)
        if not isinstance(raw, list):
            continue
        cleaned = [
            text for text in (
                _clean_untrusted_text(item, heading_cap) for item in raw
            ) if text
        ][:max_headings]
        if cleaned:
            out[dest_key] = cleaned

    # Provenance, and only when there is text for it to date. The page says
    # "reproduced verbatim from the Wayback Machine capture of X on DATE —
    # this is the previous owner's content, not ours", which is what makes
    # quoting a spam page honest instead of misleading. If the date resolved
    # from the sidecar alone it would disappear the moment the domain rolled
    # out of it, leaving undated third-party content standing as evidence.
    # A lone timestamp with no text would be the mirror-image fault: a date
    # attached to nothing.
    if any(key.startswith("excerpt_") for key in out):
        # Wayback timestamps are 14 digits, but this is still third-party
        # data and gets the same cleaning and quoting as the prose.
        stamp = _clean_untrusted_text(excerpt.get("snapshot_timestamp"), field_cap)
        if stamp:
            out["excerpt_snapshot_timestamp"] = stamp
    return out


def _build_frontmatter(
    record: dict,
    archived_date: str,
    *,
    excerpt: dict | None = None,
    config: dict | None = None,
) -> str:
    """YAML frontmatter that Astro's content collection schema parses. Keys
    match the zod schema in src/content/config.ts — adding or renaming a
    field requires updating both.

    The first thirteen keys are the original, required contract and are
    emitted unconditionally, in order, for every page. The evidence keys
    from `_evidence_fields` follow and are emitted only when present.
    """
    payload = {
        "name": record["name"],
        "tld": record["tld"],
        "verdict": record["verdict"],
        "score": int(record.get("score") or 0),
        "dropped_date": record.get("dropped_date") or archived_date,
        "archived_date": archived_date,
        "wayback_snapshots": record.get("wayback_snapshots"),
        "wayback_last_snapshot": record.get("wayback_last_snapshot"),
        "open_page_rank": record.get("open_page_rank"),
        "cc_source_domain_count": record.get("cc_source_domain_count"),
        "cert_history": record.get("cert_history"),
        "first_seen_date": record.get("first_seen_date"),
        "availability_verified_at": record.get("availability_verified_at"),
    }
    payload.update(_evidence_fields(record, excerpt, config))
    lines = ["---"]
    for k, v in payload.items():
        if v is None:
            lines.append(f"{k}: null")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            lines.append(f"{k}: {v}")
        elif isinstance(v, list):
            lines.append(f"{k}: {_yaml_string_list(v)}")
        else:
            lines.append(f"{k}: {_yaml_quote(str(v))}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def _build_markdown_file(
    record: dict,
    body: str,
    archived_date: str,
    *,
    excerpt: dict | None = None,
    config: dict | None = None,
) -> str:
    """Full file content: frontmatter + blank line + body + trailing newline."""
    frontmatter = _build_frontmatter(
        record, archived_date, excerpt=excerpt, config=config,
    )
    return frontmatter + "\n" + body.rstrip() + "\n"


def _index_entry(record: dict, archived_date: str) -> dict:
    """One archive-index.json row. Deliberately a subset of the frontmatter —
    the index feeds the archive listing page, not the detail page."""
    name = record["name"]
    return {
        "name": name,
        "tld": record.get("tld") or name.rsplit(".", 1)[-1],
        "verdict": record["verdict"],
        "score": int(record.get("score") or 0),
        "dropped_date": record.get("dropped_date"),
        "archived_date": archived_date,
        "wayback_snapshots": record.get("wayback_snapshots"),
        "cc_source_domain_count": record.get("cc_source_domain_count"),
        "open_page_rank": record.get("open_page_rank"),
    }


# --- I/O helpers -------------------------------------------------------------


def _load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        logger.warning("Could not read %s (%s); using default.", path, exc)
        return default


def _atomic_write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, indent=2, sort_keys=False)
            fh.write("\n")
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# --- Backend client ----------------------------------------------------------


class ArchivePageClient:
    """One archive page per call, over an scripts.llm_backend Backend.

    Deliberately thin — the backend owns transport, auth and timeouts. The
    system prompt is chosen per call by the caller (grounded vs no-excerpt),
    so it is passed in rather than owned here.

    `generate` raises llm_backend.LLMBackendError and nothing else from the
    backend; callers treat that as a per-domain soft failure (hard rule 17).
    """

    def __init__(self, backend: Any, *, timeout_seconds: int | None = None) -> None:
        self._backend = backend
        self._timeout = timeout_seconds

    @property
    def backend_name(self) -> str:
        return str(getattr(self._backend, "name", "unknown"))

    def generate(self, system: str, user: str) -> str:
        text = self._backend.complete(
            system=system, user=user, timeout_seconds=self._timeout,
        )
        return (text or "").strip()


def make_default_client(config: dict | None = None) -> ArchivePageClient:
    """Build the client named by ``config["llm"]["backend"]``.

    An unconstructable backend is a config error, which hard rule 17 puts in
    the crash-the-run column — unlike the classifier, this module produces no
    useful output at all without a backend, so failing soft would just write
    nothing and report success.
    """
    try:
        backend = llm_backend.get_backend(config or {})
    except llm_backend.LLMBackendError as exc:
        raise RuntimeError(f"no usable LLM backend: {exc}") from exc
    client = ArchivePageClient(
        backend, timeout_seconds=cfg(config, "timeout_seconds"),
    )
    logger.info("archive_generator: using llm backend %r", client.backend_name)
    return client


def _generate_body(client: Any, record: dict, excerpt: dict | None) -> str:
    """One page body. Picks the prompt mode from the excerpt and calls the
    client. Propagates whatever the client raises — callers decide."""
    has_excerpt = _excerpt_has_content(excerpt)
    logger.debug(
        "Generating %s in %s mode",
        record.get("name"),
        "grounded" if has_excerpt else "no-excerpt",
    )
    return client.generate(
        system=build_system_prompt(has_excerpt),
        user=_build_user_message(record, excerpt),
    )


# --- Git operations ----------------------------------------------------------


def _git(args: list[str], *, cwd: Path = REPO_ROOT, check: bool = True) -> subprocess.CompletedProcess:
    """Run a git subprocess. Captures output for the log."""
    return subprocess.run(
        ["git", *args], cwd=str(cwd), check=check,
        capture_output=True, text=True,
    )


def _git_commit_and_push(
    new_count: int, today: date, github_token: str,
) -> None:
    """Stage the archive deltas, commit, push. Token goes in the push URL
    argv only — never written to .git/config."""
    _git(["config", "user.name", GIT_USER_NAME])
    _git(["config", "user.email", GIT_USER_EMAIL])
    _git(["add", "src/content/archive", "src/data/archive-index.json"])
    diff = _git(["diff", "--cached", "--quiet"], check=False)
    if diff.returncode == 0:
        logger.info("No staged changes to commit (no new archive entries).")
        return
    msg = f"archive: add {new_count} new pages for {today.isoformat()}"
    _git(["commit", "-m", msg])
    push_url = GITHUB_REPO_URL_TEMPLATE.format(token=github_token)
    push = subprocess.run(
        ["git", "push", push_url, "main"],
        cwd=str(REPO_ROOT), capture_output=True, text=True,
    )
    if push.returncode != 0:
        # Don't dump push.stderr — it may echo back the URL in some git
        # versions. Just log the exit code; operator can inspect manually.
        raise RuntimeError(
            f"git push failed with exit code {push.returncode}; local commit "
            f"is in place. Inspect and resolve manually before next run."
        )
    logger.info("Pushed commit: %s", msg)


# --- Wayback excerpt resolution (sidecar-first, fetch-fallback) ------------


def _load_sidecar_excerpts(
    sidecar_path: Path = SIDECAR_EXCERPTS_PATH,
) -> dict[str, dict | None]:
    """Load the wayback_excerpts.json sidecar into a name → excerpt map.

    Returns an empty dict on missing OR corrupt sidecar — caller then falls
    back to per-domain `fetch_excerpt` for every domain (same path as
    pre-Phase-4 behaviour). A logged warning surfaces the degraded state
    in the daily report email.
    """
    if not sidecar_path.exists():
        logger.info(
            "Sidecar %s not present — will fetch each excerpt from Wayback directly.",
            sidecar_path,
        )
        return {}
    try:
        with open(sidecar_path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError) as exc:
        logger.warning(
            "Sidecar %s unreadable (%s); falling back to per-domain fetch.",
            sidecar_path, exc,
        )
        return {}
    if not isinstance(data, dict):
        logger.warning(
            "Sidecar %s is not a dict (got %s); falling back to per-domain fetch.",
            sidecar_path, type(data).__name__,
        )
        return {}
    return data


def _resolve_excerpt(
    record: dict, sidecar: dict[str, dict | None],
) -> tuple[dict | None, str]:
    """Return (excerpt, source) for a domain record.

    `source` is one of:
      - "sidecar-hit"  — sidecar had a dict; no archive.org call
      - "sidecar-null" — sidecar had explicit None; classifier saw this
                         domain but Wayback returned no usable content;
                         do NOT refetch (would just produce None again
                         for any persistent-state reason)
      - "fetch"        — sidecar absent for this name; called fetch_excerpt
                         (caller should sleep 1s after this — archive.org
                         courtesy)
      - "fetch-error"  — fetch_excerpt raised (transient or persistent;
                         logged warning); caller treats as None and still
                         sleeps to honor pacing
      - "no-snapshot"  — record has no wayback_last_snapshot AND not in
                         sidecar; nothing to do (no API hit, no sleep)

    The sidecar-null branch is the key correctness bit: if Phase 4's
    classifier ran on this domain and got None back from fetch_excerpt,
    refetching here would either get None again (persistent: no closest
    snapshot, all content fields empty, etc.) OR worse — racing the
    classifier's verdict by using a different snapshot than what the
    classifier saw. Trust the classifier's view, don't second-guess it.
    """
    name = record["name"]
    if name in sidecar:
        cached = sidecar[name]
        if cached is None:
            return None, "sidecar-null"
        if isinstance(cached, dict):
            return cached, "sidecar-hit"
        # Sidecar has a non-dict, non-None value — corruption. Fall through
        # to fetch as a defensive fallback rather than passing garbage to
        # the model.
        logger.warning(
            "Sidecar entry for %s is not dict|None (got %s); falling back to fetch.",
            name, type(cached).__name__,
        )

    last_snapshot = record.get("wayback_last_snapshot")
    if not last_snapshot:
        return None, "no-snapshot"

    try:
        excerpt = fetch_excerpt(name, last_snapshot)
    except Exception as exc:
        logger.warning(
            "Wayback excerpt fetch failed for %s: %s — proceeding without grounding",
            name, exc,
        )
        return None, "fetch-error"
    return excerpt, "fetch"


# --- Top-level orchestration ------------------------------------------------


def generate_archive(
    *,
    daily_path: Path = DAILY_DOMAINS_PATH,
    index_path: Path = ARCHIVE_INDEX_PATH,
    content_dir: Path = ARCHIVE_CONTENT_DIR,
    client: Any | None = None,
    today: date | None = None,
    git_push: bool = True,
    github_token: str | None = None,
    config: dict | None = None,
) -> dict:
    """Process today's daily-domains.json into archive pages. Returns a
    status dict with counts. Raises on systemic failures (config error,
    breaker tripped, push failed)."""
    today = today or date.today()
    today_iso = today.isoformat()
    config = config or {}

    daily_payload = _load_json(daily_path, default={"domains": []})
    domains = daily_payload.get("domains") or []
    if not domains:
        logger.info("daily-domains.json has no entries; nothing to archive.")
        return {"status": "no_input", "new_count": 0}

    index_payload = _load_json(index_path, default={"generated_at": None, "entries": []})
    archived_entries: list[dict] = index_payload.get("entries") or []
    already = {e.get("name") for e in archived_entries if e.get("name")}

    qualifying = _filter_qualifying(domains, already)
    if not qualifying:
        logger.info(
            "No new qualifying domains (%d in payload, %d already archived).",
            len(domains), len(already),
        )
        return {"status": "no_new", "new_count": 0}

    logger.info(
        "Processing %d new qualifying domains (of %d in payload, %d already archived).",
        len(qualifying), len(domains), len(already),
    )

    if client is None:
        client = make_default_client(config)

    content_dir.mkdir(parents=True, exist_ok=True)
    abort_after = int(cfg(config, "consecutive_failures_abort"))

    # Sidecar-first excerpt resolution (Phase 4, 2026-05-20): pipeline's
    # Stage 4b populates src/data/wayback_excerpts.json so this loop hits
    # the sidecar instead of archive.org for every classified domain.
    # Per-domain fetch_excerpt is still the fallback for entries the
    # classifier didn't see (e.g., backfilled carryover from before Phase
    # 4 wire-in, or a day where Stage 4b's sidecar write failed).
    sidecar_excerpts = _load_sidecar_excerpts(_sidecar_path_from_config(config))

    new_entries: list[dict] = []
    grounded_count = 0
    consecutive_failures = 0
    for record in qualifying:
        name = record["name"]
        md_path = content_dir / f"{_slug_for(name)}.md"

        # Second gate, after the archive-index one: a page already on disk is
        # never regenerated. Costs nothing to check and makes a lost or
        # rolled-back index entry self-heal without re-spending a model call
        # or churning an existing published page.
        if md_path.exists():
            logger.info(
                "%s already has a page at %s but is missing from the index; "
                "restoring the index entry without regenerating.",
                name, md_path.name,
            )
            new_entries.append(_index_entry(record, today_iso))
            already.add(name)
            continue

        excerpt, source = _resolve_excerpt(record, sidecar_excerpts)
        # Only pause AFTER a real archive.org hit (not after a sidecar
        # lookup). On full-sidecar-coverage days the archive run drops
        # from ~50s/run of pacing waits to ~0s.
        if source in ("fetch", "fetch-error"):
            time.sleep(1.0)

        try:
            body = _generate_body(client, record, excerpt)
        except Exception as exc:
            consecutive_failures += 1
            logger.warning(
                "Backend call failed for %s (%d/%d consecutive): %s",
                name, consecutive_failures, abort_after, exc,
            )
            if consecutive_failures >= abort_after:
                raise RuntimeError(
                    f"{abort_after} consecutive backend failures; "
                    f"circuit breaker open. Inspect the LLM backend and retry."
                ) from exc
            continue

        if not body or "##" not in body:
            consecutive_failures += 1
            logger.warning(
                "Backend returned empty / malformed body for %s; skipping.", name,
            )
            if consecutive_failures >= abort_after:
                raise RuntimeError(
                    f"{abort_after} consecutive malformed responses; "
                    f"circuit breaker open."
                )
            continue
        consecutive_failures = 0

        _atomic_write_text(
            md_path,
            _build_markdown_file(
                record, body, today_iso, excerpt=excerpt, config=config,
            ),
        )
        new_entries.append(_index_entry(record, today_iso))
        already.add(name)
        if _excerpt_has_content(excerpt):
            grounded_count += 1
        logger.info(
            "Archived %s → %s (%s)",
            name, md_path.name,
            "grounded" if _excerpt_has_content(excerpt) else "no-excerpt",
        )

    if new_entries:
        archived_entries.extend(new_entries)
        index_payload = {
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "entries": archived_entries,
        }
        _atomic_write_json(index_path, index_payload)
        logger.info(
            "Updated archive-index: +%d new, %d total entries.",
            len(new_entries), len(archived_entries),
        )
        logger.info(
            "Grounding coverage: %d/%d pages written from a Wayback excerpt.",
            grounded_count, len(new_entries),
        )

    if git_push and new_entries:
        token = github_token or (os.environ.get("GITHUB_TOKEN") or "").strip()
        if not token:
            raise RuntimeError("GITHUB_TOKEN missing — required for push.")
        _git_commit_and_push(len(new_entries), today, token)

    return {
        "status": "ok",
        "new_count": len(new_entries),
        "total_archived": len(archived_entries),
        "attempted": len(qualifying),
        "grounded_count": grounded_count,
    }


# --- Dry-run helper for pre-merge review (2026-05-18) -----------------------


def _render_one_page(
    record: dict,
    *,
    excerpt: dict | None,
    client: Any,
    output_dir: Path,
    today_iso: str,
    config: dict | None = None,
) -> tuple[bool, str | None]:
    """Per-domain work: backend call → write .md. Excerpt is provided by the
    caller (so this helper doesn't decide whether to fetch vs read sidecar
    vs use None).

    Returns (success, reason). reason is None on success, a short string
    on failure ('backend-error', 'backend-malformed'). Caller decides whether
    a failure aborts the run or just logs.

    Phase 4 (2026-05-20): excerpt-fetching responsibility moved out to
    the callers (`generate_archive` and `generate_for_domains`) so the
    sidecar-first lookup pattern works uniformly for both production and
    dry-run paths."""
    name = record["name"]

    try:
        body = _generate_body(client, record, excerpt)
    except Exception as exc:
        logger.warning("Backend call failed for %s: %s", name, exc)
        return False, "backend-error"

    if not body or "##" not in body:
        logger.warning("Backend returned empty / malformed body for %s; skipping.", name)
        return False, "backend-malformed"

    slug = _slug_for(name)
    md_path = output_dir / f"{slug}.md"
    _atomic_write_text(
        md_path,
        _build_markdown_file(record, body, today_iso, excerpt=excerpt, config=config),
    )
    logger.info("Rendered %s → %s", name, md_path)
    return True, None


def generate_for_domains(
    domain_names: list[str],
    output_dir: Path,
    *,
    daily_path: Path = DAILY_DOMAINS_PATH,
    client: Any | None = None,
    today: date | None = None,
    config: dict | None = None,
) -> dict:
    """Dry-run: process ONLY the named domains, write to `output_dir`,
    do NOT update archive-index.json, do NOT push.

    Used for pre-merge review — picks the named records out of the
    current daily-domains.json (so the input data is real, just the
    output destination is a scratch dir). Domains not present in
    daily-domains.json are reported as missing. Domains present but
    without a qualifying verdict are reported as skipped (we still
    only generate /d/{name}-style content for Clean + Promising, even
    in dry-run; protects against accidentally rendering a page for a
    Caution domain).

    Per-domain failures isolate but never abort — for 1-2 review
    samples the circuit-breaker semantics are noise, not signal.

    Returns: {"rendered": [name, ...], "missing": [...], "skipped_verdict": [...], "failed": [...]}.
    """
    today = today or date.today()
    today_iso = today.isoformat()
    config = config or {}

    daily_payload = _load_json(daily_path, default={"domains": []})
    by_name = {d["name"]: d for d in (daily_payload.get("domains") or []) if d.get("name")}

    requested = [n.strip() for n in domain_names if n.strip()]
    missing = [n for n in requested if n not in by_name]
    found = [by_name[n] for n in requested if n in by_name]
    skipped_verdict = [d["name"] for d in found if d.get("verdict") not in QUALIFYING_VERDICTS]
    eligible = [d for d in found if d.get("verdict") in QUALIFYING_VERDICTS]

    if missing:
        logger.warning(
            "Names not present in daily-domains.json (skipping): %s", missing,
        )
    if skipped_verdict:
        logger.warning(
            "Names present but verdict not in {Clean, Promising} (skipping): %s",
            skipped_verdict,
        )
    if not eligible:
        logger.error("No eligible domains to render. Stopping.")
        return {
            "rendered": [], "missing": missing,
            "skipped_verdict": skipped_verdict, "failed": [],
        }

    if client is None:
        client = make_default_client(config)

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Sidecar-first excerpt resolution, same as generate_archive (Phase 4).
    # Dry-run path benefits more from sidecar hits than the production
    # path (typical dry-run targets are 1-2 specific named domains that
    # were classified earlier today / yesterday).
    sidecar_excerpts = _load_sidecar_excerpts(_sidecar_path_from_config(config))

    rendered: list[str] = []
    failed: list[str] = []
    for record in eligible:
        excerpt, source = _resolve_excerpt(record, sidecar_excerpts)
        if source in ("fetch", "fetch-error"):
            time.sleep(1.0)
        ok, _reason = _render_one_page(
            record,
            excerpt=excerpt,
            client=client,
            output_dir=output_dir,
            today_iso=today_iso,
            config=config,
        )
        if ok:
            rendered.append(record["name"])
        else:
            failed.append(record["name"])

    logger.info(
        "Dry-run complete: %d rendered, %d failed, %d missing, %d skipped (verdict)",
        len(rendered), len(failed), len(missing), len(skipped_verdict),
    )
    return {
        "rendered": rendered,
        "missing": missing,
        "skipped_verdict": skipped_verdict,
        "failed": failed,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="scripts.archive_generator",
        description="Generate archive pages for Clean and Promising domains.",
    )
    parser.add_argument(
        "--no-push", action="store_true",
        help="Skip the git commit + push at the end. Files still written.",
    )
    parser.add_argument(
        "--daily-path", default=str(DAILY_DOMAINS_PATH),
        help="Override daily-domains.json path (default: src/data/daily-domains.json)",
    )
    parser.add_argument(
        "--index-path", default=str(ARCHIVE_INDEX_PATH),
        help="Override archive-index.json path.",
    )
    parser.add_argument(
        "--config", default=str(CONFIG_PATH),
        help=(
            "Path to config.json (carries llm.backend plus the "
            "archive_generator.* knobs)."
        ),
    )
    parser.add_argument(
        "--only", default=None,
        help=(
            "Dry-run: comma-separated domain names. Processes ONLY these "
            "domains (pulled from daily-domains.json), writes .md files to "
            "--output-dir, does NOT update archive-index.json, does NOT "
            "git-push. Intended for pre-merge review."
        ),
    )
    parser.add_argument(
        "--output-dir", default=None,
        help=(
            "Required with --only. Destination directory for the dry-run "
            ".md files. src/content/archive/ is left untouched."
        ),
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
        stream=sys.stdout,
    )

    config = _load_json(Path(args.config), default={}) or {}

    # Dry-run branch: --only + --output-dir bypass the production path
    # entirely. No index update, no git push, no archive-index gate.
    if args.only or args.output_dir:
        if not (args.only and args.output_dir):
            logger.error("--only and --output-dir must be passed together.")
            return 1
        names = [n.strip() for n in args.only.split(",") if n.strip()]
        if not names:
            logger.error("--only was empty after splitting on commas.")
            return 1
        try:
            result = generate_for_domains(
                names,
                Path(args.output_dir),
                daily_path=Path(args.daily_path),
                config=config,
            )
        except RuntimeError as exc:
            logger.error("Dry-run aborted: %s", exc)
            return 2
        except Exception:  # pragma: no cover — defence-in-depth
            logger.exception("Dry-run crashed.")
            return 3
        logger.info("Dry-run summary: %s", result)
        return 0

    try:
        result = generate_archive(
            daily_path=Path(args.daily_path),
            index_path=Path(args.index_path),
            git_push=not args.no_push,
            config=config,
        )
    except RuntimeError as exc:
        logger.error("Archive run aborted: %s", exc)
        return 2
    except Exception:  # pragma: no cover — defence-in-depth
        logger.exception("Archive run crashed.")
        return 3

    logger.info("Run summary: %s", result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
